CREATE TABLE heroes(
id SERIAL PRIMARY KEY,
name VARCHAR(255) NOT NULL,
age INTEGER NOT NULL,
special_power TEXT NOT NULL,
weakness TEXT NOT NULL,
squad_id INTEGER);

CREATE TABLE squads(
id SERIAL PRIMARY KEY,
name VARCHAR(255) NOT NULL,
role TEXT NOT NULL);

DROP TABLE squad;