/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hero.squad;

import static spark.Spark.*;

import spark.ModelAndView;
import spark.template.handlebars.HandlebarsTemplateEngine;
import org.sql2o.Sql2o;
import hero.squad.dao.Sql2oHeroDAO;
import hero.squad.models.Hero;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class App {

    private static final String connectionString = "jdbc:postgresql://localhost:5432/herodb";

    public static void main(String[] args) {
        Sql2o sql2o = new Sql2o(connectionString, "postgres", "Logger33");
        Sql2oHeroDAO heroDAO = new Sql2oHeroDAO(sql2o);
        port(8000);

        get("/heroes", (req, res) -> {
            Map<String, Object> model = new HashMap<>();
            List<Hero> heroes = heroDAO.getAll();
            model.put("url", "/heroes");
            model.put("title", "Heroes");
            model.put("heroes", heroes);
            return new ModelAndView(model, "heroes.hbs");
        }, new HandlebarsTemplateEngine());

        post("/heroes", (req, res) -> {
            String name = req.queryParams("name");
            Integer age = Integer.parseInt(req.queryParams("age"));
            String specialPower = req.queryParams("special_power");
            String weakness = req.queryParams("weakness");
            Hero newHero = new Hero(name, age, specialPower, weakness);
            heroDAO.add(newHero);
            res.redirect("/heroes");
            return null;
        }, new HandlebarsTemplateEngine());
    }
}
